const BASE='https://raw.githubusercontent.com/kyleboucher09-crypto/EFL-dynasty/case-12-25-site/case-12-25/';const A={};const PARTS={contract:2,blueprint:3,snow:3};async function txt(u){const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw new Error('asset '+r.status+' '+u);return (await r.text()).trim()}async function load(k){if(A[k])return A[k];let b;if(k==='hero')b=await txt(BASE+'assets/hero-scene.webp.b64');else if(k==='poster')b=await txt(BASE+'assets/interview-poster.webp.b64');else if(k==='collage')b=await txt(BASE+'assets-v2/collage.b64');else if(PARTS[k]){const a=[];for(let i=1;i<=PARTS[k];i++)a.push(await txt(BASE+'assets-v2/'+k+'-'+i+'.txt'));b=a.join('')}else throw new Error('Unknown asset '+k);return A[k]='data:image/webp;base64,'+b}async function boot(){try{let h=await load('hero');document.documentElement.style.setProperty('--hero','url("'+h+'")');for(let el of document.querySelectorAll('[data-asset]')){try{el.src=await load(el.dataset.asset)}catch(e){console.error(e);el.classList.add('asset-error')}}}catch(e){console.error(e)}}boot();async function openAsset(k,t){pic(await load(k),t)}function T(){let x=new Date(2026,11,25)-new Date();if(x<0)x=0;d.textContent=Math.floor(x/864e5);h.textContent=String(Math.floor(x%864e5/36e5)).padStart(2,'0');m.textContent=String(Math.floor(x%36e5/6e4)).padStart(2,'0');s.textContent=String(Math.floor(x%6e4/1e3)).padStart(2,'0')}T();setInterval(T,1e3);function pic(u,t){ii.src=u;it.textContent=t;img.showModal()}function info(t,x){ft.textContent=t;fx.textContent=x;inf.showModal()}document.querySelectorAll('dialog').forEach(x=>x.onclick=e=>{if(e.target===x)x.close()})
const RSVP_KEY='case1225-rsvp-v1';
const gate=document.getElementById('rsvpGate');
const formView=document.getElementById('rsvpFormView');
const ackView=document.getElementById('rsvpAckView');
const rsvpForm=document.getElementById('rsvpForm');
const clearanceField=document.getElementById('clearanceField');
const shareStatus=document.getElementById('rsvpShareStatus');
let currentRsvp=null;
function attendanceValue(){const x=rsvpForm.querySelector('input[name="attendance"]:checked');return x?x.value:''}
function clearanceValue(){const x=rsvpForm.querySelector('input[name="clearance"]:checked');return x?x.value:'NOT APPLICABLE'}
function setClearanceState(){const yes=attendanceValue().startsWith('YES');clearanceField.classList.toggle('dimmed',!yes);clearanceField.querySelectorAll('input').forEach(x=>{x.required=yes;if(!yes)x.checked=false})}
function openRsvp(edit=false){document.body.classList.add('rsvp-locked');gate.classList.add('open');gate.setAttribute('aria-hidden','false');formView.hidden=false;ackView.hidden=true;shareStatus.textContent='';if(edit){try{const r=JSON.parse(localStorage.getItem(RSVP_KEY)||'null');if(r){rsvpName.value=r.name||'';rsvpNote.value=r.note||'';const a=[...rsvpForm.querySelectorAll('input[name="attendance"]')].find(x=>x.value===r.attendance);if(a)a.checked=true;const c=[...rsvpForm.querySelectorAll('input[name="clearance"]')].find(x=>x.value===r.clearance);if(c)c.checked=true}}catch(e){}setClearanceState()}}
function closeRsvp(){gate.classList.remove('open');gate.setAttribute('aria-hidden','true');document.body.classList.remove('rsvp-locked')}
function rsvpText(r){return `CASE 12-25 — ATTENDANCE RECORD\nName: ${r.name}\nAttendance: ${r.attendance}\nParticipation clearance: ${r.clearance}\n${r.note?'Note: '+r.note+'\n':''}Filed: ${new Date(r.filedAt).toLocaleString()}\n\nCASE 12-25 • Christmas 2026`}
async function transmitRsvp(){if(!currentRsvp)return;const text=rsvpText(currentRsvp);try{if(navigator.share){await navigator.share({title:'CASE 12-25 RSVP',text});shareStatus.textContent='TRANSMISSION OPENED — send this record to Detective Boucher.'}else if(navigator.clipboard){await navigator.clipboard.writeText(text);shareStatus.textContent='RSVP RECORD COPIED — send it to Detective Boucher.'}else{shareStatus.textContent='Your RSVP is filed on this device. Please send your attendance status to Detective Boucher.'}}catch(e){if(e&&e.name!=='AbortError')shareStatus.textContent='Transmission interrupted. Your RSVP is still filed on this device.'}}
rsvpForm?.addEventListener('change',e=>{if(e.target.name==='attendance')setClearanceState()});
rsvpForm?.addEventListener('submit',e=>{e.preventDefault();setClearanceState();if(!rsvpForm.reportValidity())return;currentRsvp={name:rsvpName.value.trim(),attendance:attendanceValue(),clearance:attendanceValue().startsWith('YES')?clearanceValue():'NOT APPLICABLE',note:rsvpNote.value.trim(),filedAt:new Date().toISOString()};localStorage.setItem(RSVP_KEY,JSON.stringify(currentRsvp));formView.hidden=true;ackView.hidden=false;gate.scrollTo({top:0,behavior:'smooth'})});
document.getElementById('shareRsvp')?.addEventListener('click',transmitRsvp);
document.getElementById('enterHQ')?.addEventListener('click',closeRsvp);
document.getElementById('updateRsvp')?.addEventListener('click',()=>openRsvp(true));
try{const saved=localStorage.getItem(RSVP_KEY);if(!saved||new URLSearchParams(location.search).get('rsvp')==='1')openRsvp(!!saved);else currentRsvp=JSON.parse(saved)}catch(e){openRsvp(false)}