const BASE='https://raw.githubusercontent.com/kyleboucher09-crypto/EFL-dynasty/case-12-25-site/case-12-25/';
const API='https://iusmszkxfumsmjjtvzfu.supabase.co/functions/v1/case-access';
const A={};const PARTS={contract:2,blueprint:3,snow:3};
async function txt(u){const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw new Error('asset '+r.status+' '+u);return (await r.text()).trim()}
async function load(k){if(A[k])return A[k];let b;if(k==='hero')b=await txt(BASE+'assets/hero-scene.webp.b64');else if(k==='poster')b=await txt(BASE+'assets/interview-poster.webp.b64');else if(k==='collage')b=await txt(BASE+'assets-v2/collage.b64');else if(PARTS[k]){const a=[];for(let i=1;i<=PARTS[k];i++)a.push(await txt(BASE+'assets-v2/'+k+'-'+i+'.txt'));b=a.join('')}else throw new Error('Unknown asset '+k);return A[k]='data:image/webp;base64,'+b}
async function bootAssets(){try{let h=await load('hero');document.documentElement.style.setProperty('--hero','url("'+h+'")');for(let el of document.querySelectorAll('[data-asset]')){try{el.src=await load(el.dataset.asset)}catch(e){console.error(e);el.classList.add('asset-error')}}}catch(e){console.error(e)}}
async function openAsset(k,t){pic(await load(k),t)}
function T(){let x=new Date(2026,11,25)-new Date();if(x<0)x=0;const D=document.getElementById('d'),H=document.getElementById('h'),M=document.getElementById('m'),S=document.getElementById('s');if(!D)return;D.textContent=Math.floor(x/864e5);H.textContent=String(Math.floor(x%864e5/36e5)).padStart(2,'0');M.textContent=String(Math.floor(x%36e5/6e4)).padStart(2,'0');S.textContent=String(Math.floor(x%6e4/1e3)).padStart(2,'0')}
function pic(u,t){const ii=document.getElementById('ii'),it=document.getElementById('it'),img=document.getElementById('img');if(ii&&it&&img){ii.src=u;it.textContent=t;img.showModal()}}
function info(t,x){const ft=document.getElementById('ft'),fx=document.getElementById('fx'),inf=document.getElementById('inf');if(ft&&fx&&inf){ft.textContent=t;fx.textContent=x;inf.showModal()}}
window.openAsset=openAsset;window.pic=pic;window.info=info;

function installGate(){const old=document.getElementById('rsvpGate');const html=`<div id="rsvpGate" class="rsvp-gate" aria-hidden="true"><div class="rsvp-shell"><div class="rsvp-filemark">CASE 12-25 • INTAKE FILE</div>
<section id="rsvpFormView" class="rsvp-card" hidden><div class="rsvp-stamp">ATTENDANCE<br><b>REQUIRED</b></div><div class="rsvp-kicker">Christmas 2026 Participation Clearance</div><h2>Attendance Registry</h2><p class="rsvp-lede">Before access to Investigation Headquarters is granted, all prospective attendees must identify themselves and confirm their status for December 25.</p><form id="rsvpForm"><label class="rsvp-label" for="rsvpName">Full name</label><input class="rsvp-input" id="rsvpName" name="name" autocomplete="name" placeholder="Enter your full name" required><fieldset class="rsvp-fieldset"><legend>Will you be attending Christmas on December 25?</legend><label class="rsvp-choice"><input type="radio" name="attendance" value="yes" required><span><b>YES</b><small>I will be there.</small></span></label><label class="rsvp-choice"><input type="radio" name="attendance" value="no"><span><b>NO</b><small>I will not be attending.</small></span></label><label class="rsvp-choice"><input type="radio" name="attendance" value="uncertain"><span><b>UNCERTAIN</b><small>I need a little more time.</small></span></label></fieldset><fieldset id="clearanceField" class="rsvp-fieldset rsvp-clearance"><legend>Requested participation clearance</legend><p class="rsvp-help">This only tells the Detective how involved you would like to be. It does not reveal any assignment.</p><label class="rsvp-choice"><input type="radio" name="clearance" value="full"><span><b>FULL CLEARANCE</b><small>I'm all in. Give me things to do.</small></span></label><label class="rsvp-choice"><input type="radio" name="clearance" value="standard"><span><b>STANDARD CLEARANCE</b><small>I want to participate, but keep it fairly casual.</small></span></label><label class="rsvp-choice"><input type="radio" name="clearance" value="observer"><span><b>OBSERVER STATUS</b><small>I'll be there, but I'd rather mostly watch and investigate.</small></span></label></fieldset><label class="rsvp-label" for="rsvpNote">Optional note for the Detective</label><textarea class="rsvp-input rsvp-textarea" id="rsvpNote" name="note" rows="3" placeholder="Anything the Detective should know? (optional)"></textarea><div id="rsvpError" class="rsvp-error" aria-live="polite"></div><button id="rsvpSubmit" class="btn red rsvp-submit" type="submit">File My RSVP →</button></form><button id="openRestore" class="rsvp-text-button" type="button">Already filed an RSVP? Restore Case Access</button></section>
<section id="rsvpRestoreView" class="rsvp-card" hidden><div class="rsvp-kicker">CASE 12-25 • Identity Recovery</div><h2>Restore Case Access</h2><p class="rsvp-lede">Use the name on your original attendance record and the CASE access code issued when you first filed.</p><form id="restoreForm"><label class="rsvp-label" for="restoreName">Full name</label><input class="rsvp-input" id="restoreName" autocomplete="name" placeholder="Enter your full name" required><label class="rsvp-label" for="restoreCode">Case access code</label><input class="rsvp-input rsvp-code-input" id="restoreCode" autocomplete="off" spellcheck="false" placeholder="CASE-XXXX-XXXX" required><div id="restoreError" class="rsvp-error" aria-live="polite"></div><button id="restoreSubmit" class="btn red rsvp-submit" type="submit">Restore Access →</button></form><button id="backToRsvp" class="rsvp-text-button" type="button">← File a new RSVP instead</button></section>
<section id="rsvpAckView" class="rsvp-card rsvp-ack" hidden><div class="rsvp-seal">FILED</div><div class="rsvp-kicker">CASE 12-25 • Attendance Registry</div><h2>RSVP Received</h2><div class="rsvp-statusline">STATUS: STORED WITH CASE 12-25</div><p>Your attendance record has been permanently filed.</p><div id="accessCodeBox" class="rsvp-access-code" hidden><small>YOUR CASE ACCESS CODE</small><strong id="accessCodeText">CASE-XXXX-XXXX</strong><p>Keep this code somewhere safe. If you change devices or clear your browser, it restores your existing record — you will not need to RSVP again.</p><button id="copyAccessCode" class="btn" type="button">Copy Access Code</button></div><p>If your presence is confirmed, the Detective may contact you privately in the coming weeks with additional instructions.</p><p>Until then, review the public case file carefully.</p><p class="rsvp-warning">Not everything released this year should be taken at face value.</p><div class="rsvp-signoff">— Detective Boucher<br><small>Lead Investigator, CASE 12-25</small></div><button id="enterHQ" class="btn red">Enter Investigation Headquarters →</button><div id="rsvpShareStatus" class="rsvp-share-status" aria-live="polite"></div></section>
<section id="rsvpOfflineView" class="rsvp-card rsvp-ack" hidden><div class="rsvp-kicker">CASE 12-25 • Records System</div><h2>Connection Interrupted</h2><p>Your device already contains CASE 12-25 access information, so <b>do not file another RSVP.</b></p><p>The records system could not be reached right now. Your existing identity has not been replaced or deleted.</p><div class="rsvp-ack-actions"><button id="retrySession" class="btn red" type="button">Retry Verification →</button><button id="continuePublic" class="btn" type="button">Continue to Public Headquarters</button></div></section></div></div>`;const t=document.createElement('template');t.innerHTML=html.trim();if(old)old.replaceWith(t.content.firstChild);else document.body.prepend(t.content.firstChild)}

const SESSION_KEY='case1225-session-v2',CLIENT_KEY='case1225-client-key-v2',ACCESS_CODE_KEY='case1225-access-code-v2';let currentIdentity=null;window.CASE_PARTICIPANT=null;
function getClientKey(){let key=localStorage.getItem(CLIENT_KEY);if(!key){key=crypto.randomUUID();localStorage.setItem(CLIENT_KEY,key)}return key}
function readSession(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch{return null}}
function saveSession(payload){const s={participant_id:payload.participant.id,session_token:payload.session_token,session_expires_at:payload.session_expires_at,display_name:payload.participant.display_name};localStorage.setItem(SESSION_KEY,JSON.stringify(s));if(payload.access_code)localStorage.setItem(ACCESS_CODE_KEY,payload.access_code);currentIdentity=payload;window.CASE_PARTICIPANT=payload;return s}
function clearSession(){localStorage.removeItem(SESSION_KEY);currentIdentity=null;window.CASE_PARTICIPANT=null}
async function api(body){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),cache:'no-store'});let data={};try{data=await r.json()}catch{}if(!r.ok){const e=new Error(data.error||'CASE 12-25 records are temporarily unavailable.');e.status=r.status;e.code=data.code;throw e}return data}
function refs(){return{gate:document.getElementById('rsvpGate'),formView:document.getElementById('rsvpFormView'),restoreView:document.getElementById('rsvpRestoreView'),ackView:document.getElementById('rsvpAckView'),offlineView:document.getElementById('rsvpOfflineView'),rsvpForm:document.getElementById('rsvpForm'),restoreForm:document.getElementById('restoreForm'),clearanceField:document.getElementById('clearanceField'),rsvpError:document.getElementById('rsvpError'),restoreError:document.getElementById('restoreError'),shareStatus:document.getElementById('rsvpShareStatus')}}
function showGate(view){const r=refs();document.body.classList.add('rsvp-locked');r.gate.classList.add('open');r.gate.setAttribute('aria-hidden','false');[r.formView,r.restoreView,r.ackView,r.offlineView].forEach(v=>v.hidden=true);view.hidden=false;r.gate.scrollTo({top:0,behavior:'auto'})}
function closeGate(){const g=document.getElementById('rsvpGate');g.classList.remove('open');g.setAttribute('aria-hidden','true');document.body.classList.remove('rsvp-locked')}
function attendanceValue(){const x=document.querySelector('#rsvpForm input[name="attendance"]:checked');return x?x.value:''}
function clearanceValue(){const x=document.querySelector('#rsvpForm input[name="clearance"]:checked');return x?x.value:'not_applicable'}
function setClearanceState(){const r=refs(),yes=attendanceValue()==='yes';r.clearanceField.classList.toggle('dimmed',!yes);r.clearanceField.querySelectorAll('input').forEach(x=>{x.required=yes;if(!yes)x.checked=false})}
function setBusy(btn,busy,label){btn.disabled=busy;btn.textContent=busy?'Filing Securely…':label}
function prefillParticipant(p){const f=document.getElementById('rsvpForm');document.getElementById('rsvpName').value=p?.display_name||'';document.getElementById('rsvpNote').value=p?.note||'';f.querySelectorAll('input[name="attendance"]').forEach(x=>x.checked=x.value===p?.attendance);f.querySelectorAll('input[name="clearance"]').forEach(x=>x.checked=x.value===p?.clearance);setClearanceState()}
function showAck(payload,newRegistration=false){currentIdentity=payload;window.CASE_PARTICIPANT=payload;const r=refs();showGate(r.ackView);const box=document.getElementById('accessCodeBox'),code=payload.access_code||localStorage.getItem(ACCESS_CODE_KEY)||'';box.hidden=!newRegistration||!code;if(code)document.getElementById('accessCodeText').textContent=code;r.shareStatus.textContent=newRegistration?'Your RSVP is now stored in the CASE 12-25 records system.':''}
function showForm(edit=false){const r=refs();r.rsvpError.textContent='';if(edit&&currentIdentity?.participant)prefillParticipant(currentIdentity.participant);showGate(r.formView)}
function showRestore(prefill=''){const r=refs();r.restoreError.textContent='';document.getElementById('restoreName').value=prefill||'';document.getElementById('restoreCode').value='';showGate(r.restoreView)}
async function verifySavedSession(){const s=readSession(),r=refs();if(!s){showForm(false);return}try{const payload=await api({action:'session',participant_id:s.participant_id,session_token:s.session_token});currentIdentity=payload;window.CASE_PARTICIPANT=payload;closeGate()}catch(e){if(e.status===401||e.code==='SESSION_INVALID'){clearSession();showRestore(s.display_name||'')}else showGate(r.offlineView)}}
function openDossier(){const p=currentIdentity?.character_profile;if(p&&p.profile_status==='released')info(p.public_title||'YOUR DOSSIER',p.private_dossier||p.public_summary||'Your dossier has been released.');else info('PERSONAL DOSSIER','Your CASE 12-25 identity is linked to this archive. No private character dossier has been released to you yet. When one is assigned, it will attach to this same participant record.')}
window.openDossier=openDossier;

function bindIdentity(){const r=refs(),dossier=document.getElementById('dossiers');if(dossier)dossier.onclick=openDossier;r.rsvpForm.addEventListener('change',e=>{if(e.target.name==='attendance')setClearanceState()});r.rsvpForm.addEventListener('submit',async e=>{e.preventDefault();setClearanceState();if(!r.rsvpForm.reportValidity())return;const btn=document.getElementById('rsvpSubmit');r.rsvpError.textContent='';const existing=readSession();try{setBusy(btn,true,'File My RSVP →');let payload;if(existing){payload=await api({action:'update_rsvp',participant_id:existing.participant_id,session_token:existing.session_token,attendance:attendanceValue(),clearance:attendanceValue()==='yes'?clearanceValue():'not_applicable',note:document.getElementById('rsvpNote').value.trim()});currentIdentity=payload;window.CASE_PARTICIPANT=payload;showAck(payload,false)}else{payload=await api({action:'register',name:document.getElementById('rsvpName').value.trim(),attendance:attendanceValue(),clearance:attendanceValue()==='yes'?clearanceValue():'not_applicable',note:document.getElementById('rsvpNote').value.trim(),client_key:getClientKey()});saveSession(payload);showAck(payload,!payload.existing)}}catch(err){if(err.code==='RESTORE_REQUIRED'){showRestore(document.getElementById('rsvpName').value.trim());refs().restoreError.textContent='A record already exists for this name. Restore that record instead of creating another.'}else if(err.status===401){clearSession();showRestore(document.getElementById('rsvpName').value.trim());refs().restoreError.textContent='Your saved access needs to be restored before this RSVP can be updated.'}else r.rsvpError.textContent=err.message||'The records system could not be reached. Nothing was lost; please try again.'}finally{setBusy(btn,false,'File My RSVP →')}});
r.restoreForm.addEventListener('submit',async e=>{e.preventDefault();if(!r.restoreForm.reportValidity())return;const btn=document.getElementById('restoreSubmit');r.restoreError.textContent='';try{setBusy(btn,true,'Restore Access →');const payload=await api({action:'restore',name:document.getElementById('restoreName').value.trim(),access_code:document.getElementById('restoreCode').value.trim()});saveSession(payload);showAck(payload,false);refs().shareStatus.textContent='CASE access restored. This device is linked to your existing record.'}catch(err){r.restoreError.textContent=err.message||'The records system could not be reached. Please try again.'}finally{setBusy(btn,false,'Restore Access →')}});
document.getElementById('openRestore').onclick=()=>showRestore(document.getElementById('rsvpName').value.trim());document.getElementById('backToRsvp').onclick=()=>showForm(false);document.getElementById('copyAccessCode').onclick=async()=>{const code=document.getElementById('accessCodeText').textContent;try{await navigator.clipboard.writeText(code);refs().shareStatus.textContent='ACCESS CODE COPIED — keep it somewhere safe.'}catch{refs().shareStatus.textContent='Please save the access code shown above somewhere safe.'}};document.getElementById('enterHQ').onclick=closeGate;const up=document.getElementById('updateRsvp');if(up)up.onclick=async()=>{const s=readSession();if(!s){showRestore('');return}try{const payload=await api({action:'session',participant_id:s.participant_id,session_token:s.session_token});currentIdentity=payload;window.CASE_PARTICIPANT=payload;showForm(true)}catch(e){if(e.status===401){clearSession();showRestore(s.display_name||'')}else showGate(refs().offlineView)}};document.getElementById('retrySession').onclick=verifySavedSession;document.getElementById('continuePublic').onclick=closeGate}

installGate();bindIdentity();bootAssets();T();setInterval(T,1000);document.querySelectorAll('dialog').forEach(x=>x.addEventListener('click',e=>{if(e.target===x)x.close()}));verifySavedSession();